import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faTimes } from "@fortawesome/free-solid-svg-icons";
const Navbar = () => {
    const location = useLocation();
    const [isOpen, setIsOpen] = useState(false);
    // Function to close the menu when a link is clicked
    const closeMenu = () => setIsOpen(false);
    return (_jsxs("nav", { className: "fixed top-0 left-0 w-full bg-gradient-to-r from-[#0a0f29] to-[#11193f] shadow-md px-6 py-4 flex justify-between items-center transition-all duration-300 z-50", children: [_jsx(Link, { to: "/", className: "text-2xl font-bold text-white tracking-wide", children: "SafeSurf" }), _jsxs("div", { className: "hidden md:flex gap-6", children: [_jsx(Link, { to: "/", className: `text-white transition-all duration-300 hover:text-blue-400 ${location.pathname === "/" ? "font-semibold border-b-2 border-blue-400" : ""}`, children: "Home" }), _jsx(Link, { to: "/all-scans", className: `text-white transition-all duration-300 hover:text-blue-400 ${location.pathname === "/all-scans" ? "font-semibold border-b-2 border-blue-400" : ""}`, children: "Scans" })] }), _jsx("button", { className: "md:hidden text-white focus:outline-none transition-transform duration-300 transform hover:scale-110 hover:text-blue-400 hover:bg-white/10 p-2 rounded-full", onClick: () => setIsOpen(!isOpen), children: _jsx(FontAwesomeIcon, { icon: isOpen ? faTimes : faBars, size: "lg" }) }), _jsxs("div", { className: `fixed top-0 left-0 w-full h-screen bg-black/60 backdrop-blur-md flex flex-col items-center justify-center transition-all duration-500 ${isOpen ? "opacity-100 visible" : "opacity-0 invisible"}`, onClick: closeMenu, children: [_jsx("button", { className: "absolute top-6 right-6 text-white text-2xl focus:outline-none transition-transform duration-300 transform hover:scale-110 hover:text-blue-400", onClick: closeMenu, children: _jsx(FontAwesomeIcon, { icon: faTimes }) }), _jsxs("div", { className: `bg-[#121a36] p-6 rounded-lg shadow-xl flex flex-col items-center gap-6 transform transition-all duration-500 ${isOpen ? "translate-y-0 opacity-100" : "-translate-y-10 opacity-0"}`, onClick: (e) => e.stopPropagation(), children: [_jsx(Link, { to: "/", className: `text-white text-lg transition-all duration-300 hover:text-blue-400 ${location.pathname === "/" ? "font-semibold border-b-2 border-blue-400" : ""}`, onClick: closeMenu, children: "Home" }), _jsx(Link, { to: "/all-scans", className: `text-white text-lg transition-all duration-300 hover:text-blue-400 ${location.pathname === "/all-scans" ? "font-semibold border-b-2 border-blue-400" : ""}`, onClick: closeMenu, children: "Scans" })] })] })] }));
};
export default Navbar;
